---
- name: reload mongodb_query_exporter unit
  systemd: daemon_reload=yes

- name: restart mongodb_query_exporter service
  systemd:
    name: "{{ mongodb_exporter_service_name }}"
    state: restarted
